import { useState, useEffect } from "react";
import QuizLoader from "./_components/QuizLoader";
import QuizIntro from "./_components/IntroductionScreen";
import QuizActive from "./_components/AssessmentScreen";
import QuizResults from "./_components/ResultsScreen";
import { QuizResult, StaticTest, UserAnswers } from "./types";
import { fetchStaticTest } from "./service";
import QuizError from "./_components/QuizError";

export type QuizState = "loading" | "ready" | "started" | "completed" | "error";
export type QuizType = "pretest" | "posttest";

interface QuizContainerProps {
  itemId: string;
  moduleId: string;
  type: QuizType;
  onContinue: () => void;
  onProgressChange?: (
    itemId: string,
    completedSteps: number,
    totalSteps: number,
  ) => void;
}

export default function QuizContainer({
  itemId,
  moduleId,
  type,
  onContinue,
  onProgressChange,
}: QuizContainerProps) {
  const [quizState, setQuizState] = useState<QuizState>("loading");
  const [test, setTest] = useState<StaticTest | null>(null);
  const [answers, setAnswers] = useState<UserAnswers>({});
  const [result, setResult] = useState<QuizResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (
      quizState === "started" ||
      quizState === "completed" ||
      quizState === "error" ||
      test !== null
    ) {
      return;
    }

    let cancelled = false;

    const fetchQuizData = async () => {
      setQuizState("loading");
      setError(null);

      try {
        const response = await fetchStaticTest(
          moduleId,
          type === "pretest" ? "pre_test" : "post_test",
        );

        console.log(response.data);
        if (cancelled) return;

        // Unpack the unified response server wrapper safely
        if (response.success && response.data) {
          // 1. This is the fully formatted client-side model generated by your service transformer
          const testData = response.data;
          setTest(testData);

          if (testData.previouslySavedAnswers) {
            setAnswers(testData.previouslySavedAnswers);
          }

          // FIX: Read properties safely from the unified client data payload
          if (testData.status === "completed") {
            const total = testData.questions?.length || 0;

            // Read the mapped score property from the frontend object structure
            const score = testData.score ?? 0;

            const passingPercentage = 0.75;
            const passed = score >= Math.ceil(total * passingPercentage);

            setResult({ score, total, passed });
            setQuizState("completed");
          } else if ((testData.currentIndex ?? 0) > 0) {
            setQuizState("started");
          } else {
            setQuizState("ready");
          }
        } else {
          // Fallback if success flag came back false from the network engine
          setError(
            response.error || "Failed to load test sequence configuration",
          );
          setQuizState("error");
        }
      } catch (err) {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : "Something went wrong");
        setQuizState("error");
      }
    };

    if (moduleId) fetchQuizData();

    return () => {
      cancelled = true;
    };
  }, [moduleId, type, quizState, test]);

  useEffect(() => {
    if (!test) return;

    onProgressChange?.(
      itemId,
      Object.keys(answers).length,
      test.questions.length,
    );
  }, [answers, itemId, onProgressChange, test]);

  const handleStartQuiz = (): void => setQuizState("started");

  const handleAnswer = (questionId: string, choiceId: string): void => {
    setAnswers((prev) => ({ ...prev, [questionId]: choiceId }));
  };

  const handleSubmit = async (finalResult?: QuizResult): Promise<void> => {
    if (!test) return;

    if (finalResult) {
      setResult(finalResult);
    } else {
      const score = test.questions.reduce((total, question) => {
        return (
          total + (answers[question.id] === question.correctAnswer ? 1 : 0)
        );
      }, 0);

      const total = test.questions.length;
      const passingPercentage = 0.75;
      const passed = score >= Math.ceil(total * passingPercentage);

      setResult({ score, total, passed });
    }

    setQuizState("completed");
  };

  return (
    <div className="h-full">
      <div className="h-full items-center justify-center bg-white p-8">
        {quizState === "loading" && <QuizLoader />}

        {quizState === "ready" && test && (
          <QuizIntro test={test} onStart={handleStartQuiz} />
        )}

        {quizState === "started" && test && (
          <QuizActive
            test={test}
            attemptId={test.attemptId}
            initialIndex={test.currentIndex ?? 0}
            answers={answers}
            onAnswer={handleAnswer}
            onSubmit={handleSubmit}
          />
        )}

        {quizState === "completed" && result && (
          <div className="flex h-full items-center justify-center">
            <QuizResults
              result={result}
              onContinue={onContinue}
              showPassFail={type === "posttest"}
            />
          </div>
        )}

        {quizState === "error" && (
          <QuizError error={error} onRetry={() => setQuizState("loading")} />
        )}
      </div>
    </div>
  );
}
